[package]
name = "rust-git-hooks"
version = "0.1.0"
authors = ["alfinsuryaS <benjaminstwo@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
git2 = "0.10"
time = "0.1"
colored = "1.9"